### ISSUE TITLE
Error in x1$col.year[ids] - validateDup

### ISSUE THREAD

**Issue by WevertonBio** [LimaRAF/plantR#86] opened 2022-02-07 04:51 UTC
Hi Renato,

I am getting the following error when I try to use the validateDup function:

_Error in x1$col.year[ids] <- as.character(sapply(strsplit(x1$col.year[ids],  : 
  NAs não são permitidos em atribuições por subscritos_

I found the piece of dataframe where the error occurs (here: [SpeciesOccurrences.csv](https://github.com/LimaRAF/plantR/files/8012386/SpeciesOccurrences.csv)), but I can not understand why the error occurs.

Could you please help me to solve this error?

**Comment by LimaRAF** [comment] 2022-02-28 20:56
Hi @WevertonBio,

Thanks for the issue and sorry for the late reply. I will try to look into this asap. Thanks for the sample data to reproduce your error. I will get back to you on this once I fix this problem.

**Comment by LimaRAF** [comment] 2022-03-02 22:42
Hi @WevertonBio,

I looked today into the problem you mentioned, and it looks like it is connected to changes in one of the package depencies (stringr). I think everything should be alright now.

Please re-install the package from the dev branch and say if you still get the same error. If you don't, please let me know so that I can close this issue.

**Comment by WevertonBio** [comment] 2022-03-04 13:54
Oi Renato,

Tudo certo agora, rodou sem erros.

Muito obrigado e parabéns pelo trabalho, o pacote tem ajudado muito por aqui.

**Comment by LimaRAF** [comment] 2022-03-04 14:04
Legal @WevertonBio, que bom que deu tudo certo! E que bom o pacote tem ajudado! Por favor, lembre sempre de citá-lo nas suas publicações!

**Closed by LimaRAF** 2022-03-04 14:04 UTC
Labels: bug
