### ISSUE TITLE
Função rspeciesLink deixou de funcionar

### ISSUE THREAD

**Issue by jaum20** [LimaRAF/plantR#101] opened 2024-02-06 18:30 UTC
Devido a mudanças na API a função não funciona mais

http://blog.cria.org.br/2024/01/comunicado-sobre-api-do-iservico-web-da.html

**Comment by KPHendriks** [comment] 2024-02-19 08:43
Hello,

I ran into the same 'problem', trying to download speciesLink data using plantR. 
Would it be possible to update the speciesLink function to access the correct API version?

Many thanks and best wishes,

Kasper

**Comment by jaum20** [comment] 2024-02-19 14:34
@KPHendriks you can use my fork. I updated the rspeciesLink function to use the new API

**Comment by KPHendriks** [comment] 2024-02-19 16:31
Awesome. Thanks!

**Comment by eliane-anunciacao** [comment] 2024-04-06 19:25
Hi. 
Could someone who was able to download data from SpeciesLink with the new API demonstrate it here?

**Comment by eliane-anunciacao** [comment] 2024-04-08 18:43
Thanks!
I tried running the modified code for the error, but was unsuccessful.

**Comment by jaum20** [comment] 2024-04-09 15:07
> Hi. Could someone who was able to download data from SpeciesLink with the new API demonstrate it here?

Whine @LimaRAF is working on this, you can use my fork. It is downloading using the new splink api

**Comment by eliane-anunciacao** [comment] 2024-04-10 11:50
Thank you for responding! I'll try using your fork. I'll let you know if I
encounter any issues.

Doutoranda em Botânica
Universidade estadual de Feira de Santana (UEFS)
Departamento de Ciências Biológicas
Avenida Transnordestina, s/n - Novo Horizonte
http://lattes.cnpq.br/4554841254009838


Em ter., 9 de abr. de 2024 às 12:07, JoaoPSVieira ***@***.***>
escreveu:

**Comment by eliane-anunciacao** [comment] 2024-04-11 12:53
Hello! @jaum20, I tried using your fork, but I was unsuccessful.

**Comment by jaum20** [comment] 2024-04-11 14:45
> [jaum20](/jaum20)

paste the error here, please

**Comment by LimaRAF** [comment] 2024-05-09 02:36
There is a new version of `rspeciesLink()` in the `dev` branch which builds on @jaum20 suggestions. Besides the API address and changes in query codes, it is now needed to get an API key to download the data. And download is now restricted to 5000 records independently on the number of species in the query. So, the sapply solution in the examples should be more useful than before. 

Please use `remotes::install_github("LimaRAF/plantR", ref = "dev")` to get this new version of the function and let me know if everything is ok on your side before I can close this issue.

**Closed** 2024-05-14 15:39 UTC
Labels: bug

**Comment by LimaRAF** [comment] 2024-05-29 18:41
Olá @jaum20 , thnaks for all the checks and helpful suggestions!

However, I could not reproduce the error you mentioned. This is a common error when using `dplyr::bind_rows()` but all my checks are passing and in both vignettes we have, everything seems fine.

Could you please send me the codes and the plantR version you used to get this error?

Thanks again
